if(NOT DEFINED CALIBRATE OR NOT DEFINED PROFILE OR NOT DEFINED REPLAY OR NOT DEFINED ROOT)
  message(FATAL_ERROR "missing cross-process test arguments")
endif()
file(REMOVE_RECURSE "${ROOT}")
file(MAKE_DIRECTORY "${ROOT}")
set(MANIFEST "${ROOT}/calibration.json")
file(WRITE "${MANIFEST}" "{\n  \"schema_version\": 1,\n  \"operation\": \"heat_diffusion\",\n  \"rows\": 48,\n  \"columns\": 48,\n  \"iterations\": 4,\n  \"repetitions\": 3,\n  \"worker_budget\": 2,\n  \"seed\": 170,\n  \"numerical_policy\": \"Reproducible\",\n  \"output_directory\": \"${ROOT}\"\n}\n")
function(run_checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT code EQUAL 0)
    message(FATAL_ERROR "command failed (${code}): ${ARGV}\nstdout=${out}\nstderr=${err}")
  endif()
endfunction()
run_checked("${CALIBRATE}" "${MANIFEST}")
run_checked("${PROFILE}" approve "${ROOT}/candidate_profile.json" "${ROOT}/approved_profile.json")
file(SHA256 "${ROOT}/approved_profile.json" PROFILE_BEFORE)
run_checked("${REPLAY}" run "${ROOT}/approved_profile.json" "${ROOT}/replay_a.json" 48 48 4 2 170)
run_checked("${REPLAY}" run "${ROOT}/approved_profile.json" "${ROOT}/replay_b.json" 48 48 4 2 170)
run_checked("${REPLAY}" compare "${ROOT}/replay_a.json" "${ROOT}/replay_b.json")
file(SHA256 "${ROOT}/approved_profile.json" PROFILE_AFTER)
if(NOT PROFILE_BEFORE STREQUAL PROFILE_AFTER)
  message(FATAL_ERROR "ReadOnly deterministic replay modified the Approved profile")
endif()
