# Expand user-friendly umbrella options into the original fine-grained options.

if(SMARTPARALLEL_BUILD_ALL)
  set(SMARTPARALLEL_BUILD_EXAMPLES ON)
  set(SMARTPARALLEL_BUILD_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_BENCHMARKS ON)
endif()

if(SMARTPARALLEL_BUILD_VALIDATION)
  set(SMARTPARALLEL_BUILD_V1_PHASE1 ON)
  set(SMARTPARALLEL_BUILD_AUTO_PROFILE_TEST ON)
  set(SMARTPARALLEL_BUILD_PARALLEL_FOR_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_PARALLEL_FOR_HARDENING ON)
  set(SMARTPARALLEL_BUILD_V140_ALGORITHM_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_V160_SCIENTIFIC_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_V170_REPRODUCIBLE_RUNTIME_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_V180_GOVERNED_EXECUTION_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_V170_TOOLS ON)
  if(SMARTPARALLEL_BUILD_VISION)
    set(SMARTPARALLEL_BUILD_V150_VISION_VALIDATION ON)
  endif()
endif()

if(SMARTPARALLEL_BUILD_REAL_WORLD_BENCHMARKS)
  set(SMARTPARALLEL_BUILD_OPENCV_BENCHMARK ON)
  set(SMARTPARALLEL_BUILD_LZ4_BENCHMARK ON)
  set(SMARTPARALLEL_BUILD_BVH_BENCHMARK ON)
  set(SMARTPARALLEL_BUILD_PARTICLE_BENCHMARK ON)
endif()

if(SMARTPARALLEL_BUILD_BENCHMARKS)
  set(SMARTPARALLEL_BUILD_PARALLEL_FOR_OVERHEAD ON)
  set(SMARTPARALLEL_BUILD_OPENCV_TEST1 ON)
  set(SMARTPARALLEL_BUILD_OPENCV_TEST2 ON)
  set(SMARTPARALLEL_BUILD_OPENCV_TEST3 ON)
  set(SMARTPARALLEL_BUILD_OPENCV_STRESS ON)
  set(SMARTPARALLEL_BUILD_SCIENTIFIC_TEST1 ON)
  set(SMARTPARALLEL_BUILD_SCIENTIFIC_TEST2 ON)
  set(SMARTPARALLEL_BUILD_SCIENTIFIC_TEST3 ON)
  set(SMARTPARALLEL_BUILD_DECISION_QUALITY_AUDIT ON)
  set(SMARTPARALLEL_BUILD_V110_NESTED_BENCHMARKS ON)
  set(SMARTPARALLEL_BUILD_V140_ALGORITHM_BENCHMARKS ON)
  set(SMARTPARALLEL_BUILD_V160_SCIENTIFIC_BENCHMARKS ON)
  set(SMARTPARALLEL_BUILD_V170_BENCHMARKS ON)
  if(SMARTPARALLEL_BUILD_VISION AND SMARTPARALLEL_ENABLE_OPENCV_PROVIDER)
    set(SMARTPARALLEL_BUILD_V150_VISION_BENCHMARKS ON)
  endif()
endif()

set(SMARTPARALLEL_BUILD_ANY_VALIDATION OFF)
if(SMARTPARALLEL_BUILD_V1_PHASE1
   OR SMARTPARALLEL_BUILD_AUTO_PROFILE_TEST
   OR SMARTPARALLEL_BUILD_PARALLEL_FOR_VALIDATION
   OR SMARTPARALLEL_BUILD_PARALLEL_FOR_HARDENING
   OR SMARTPARALLEL_BUILD_V140_ALGORITHM_VALIDATION
   OR SMARTPARALLEL_BUILD_V150_VISION_VALIDATION
   OR SMARTPARALLEL_BUILD_V160_SCIENTIFIC_VALIDATION
   OR SMARTPARALLEL_BUILD_V170_REPRODUCIBLE_RUNTIME_VALIDATION
   OR SMARTPARALLEL_BUILD_V180_GOVERNED_EXECUTION_VALIDATION
   OR SMARTPARALLEL_BUILD_PARALLEL_FOR_OVERHEAD)
  set(SMARTPARALLEL_BUILD_ANY_VALIDATION ON)
endif()

set(SMARTPARALLEL_BUILD_ANY_BENCHMARK OFF)
if(SMARTPARALLEL_BUILD_OPENCV_TEST1
   OR SMARTPARALLEL_BUILD_OPENCV_TEST2
   OR SMARTPARALLEL_BUILD_OPENCV_TEST3
   OR SMARTPARALLEL_BUILD_OPENCV_STRESS
   OR SMARTPARALLEL_BUILD_SCIENTIFIC_TEST1
   OR SMARTPARALLEL_BUILD_SCIENTIFIC_TEST2
   OR SMARTPARALLEL_BUILD_SCIENTIFIC_TEST3
   OR SMARTPARALLEL_BUILD_DECISION_QUALITY_AUDIT
   OR SMARTPARALLEL_BUILD_V110_NESTED_BENCHMARKS
   OR SMARTPARALLEL_BUILD_V140_ALGORITHM_BENCHMARKS
   OR SMARTPARALLEL_BUILD_V150_VISION_BENCHMARKS
   OR SMARTPARALLEL_BUILD_V160_SCIENTIFIC_BENCHMARKS
   OR SMARTPARALLEL_BUILD_V170_BENCHMARKS
   OR SMARTPARALLEL_BUILD_V180_BENCHMARKS
   OR SMARTPARALLEL_BUILD_OPENCV_BENCHMARK
   OR SMARTPARALLEL_BUILD_LZ4_BENCHMARK
   OR SMARTPARALLEL_BUILD_BVH_BENCHMARK
   OR SMARTPARALLEL_BUILD_PARTICLE_BENCHMARK)
  set(SMARTPARALLEL_BUILD_ANY_BENCHMARK ON)
endif()
