# Expand user-friendly umbrella options into the original fine-grained options.

if(SMARTPARALLEL_BUILD_ALL)
  set(SMARTPARALLEL_BUILD_EXAMPLES ON)
  set(SMARTPARALLEL_BUILD_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_BENCHMARKS ON)
endif()

if(SMARTPARALLEL_BUILD_VALIDATION)
  set(SMARTPARALLEL_BUILD_V1_PHASE1 ON)
  set(SMARTPARALLEL_BUILD_AUTO_PROFILE_TEST ON)
  set(SMARTPARALLEL_BUILD_PARALLEL_FOR_VALIDATION ON)
  set(SMARTPARALLEL_BUILD_PARALLEL_FOR_HARDENING ON)
endif()

if(SMARTPARALLEL_BUILD_BENCHMARKS)
  set(SMARTPARALLEL_BUILD_PARALLEL_FOR_OVERHEAD ON)
  set(SMARTPARALLEL_BUILD_OPENCV_TEST1 ON)
  set(SMARTPARALLEL_BUILD_OPENCV_TEST2 ON)
  set(SMARTPARALLEL_BUILD_OPENCV_TEST3 ON)
  set(SMARTPARALLEL_BUILD_OPENCV_STRESS ON)
  set(SMARTPARALLEL_BUILD_SCIENTIFIC_TEST1 ON)
  set(SMARTPARALLEL_BUILD_SCIENTIFIC_TEST2 ON)
  set(SMARTPARALLEL_BUILD_SCIENTIFIC_TEST3 ON)
  set(SMARTPARALLEL_BUILD_DECISION_QUALITY_AUDIT ON)
endif()

set(SMARTPARALLEL_BUILD_ANY_VALIDATION OFF)
if(SMARTPARALLEL_BUILD_V1_PHASE1
   OR SMARTPARALLEL_BUILD_AUTO_PROFILE_TEST
   OR SMARTPARALLEL_BUILD_PARALLEL_FOR_VALIDATION
   OR SMARTPARALLEL_BUILD_PARALLEL_FOR_HARDENING
   OR SMARTPARALLEL_BUILD_PARALLEL_FOR_OVERHEAD)
  set(SMARTPARALLEL_BUILD_ANY_VALIDATION ON)
endif()

set(SMARTPARALLEL_BUILD_ANY_BENCHMARK OFF)
if(SMARTPARALLEL_BUILD_OPENCV_TEST1
   OR SMARTPARALLEL_BUILD_OPENCV_TEST2
   OR SMARTPARALLEL_BUILD_OPENCV_TEST3
   OR SMARTPARALLEL_BUILD_OPENCV_STRESS
   OR SMARTPARALLEL_BUILD_SCIENTIFIC_TEST1
   OR SMARTPARALLEL_BUILD_SCIENTIFIC_TEST2
   OR SMARTPARALLEL_BUILD_SCIENTIFIC_TEST3
   OR SMARTPARALLEL_BUILD_DECISION_QUALITY_AUDIT)
  set(SMARTPARALLEL_BUILD_ANY_BENCHMARK ON)
endif()
